/*
 * webrgss.c — top-level entry points for the WebRGSS WASM mruby runtime.
 *
 * This file is the bridge between the Emscripten wrapper (webrgss.mjs) and
 * the mruby VM. It exposes five symbols that WasmRgssRuntime.ts binds:
 *
 *   int   _wrgss_init(void);                           // create mrb state
 *   int   _wrgss_exec_script(const char *src,
 *                            const char *name);        // eval a Ruby string
 *   int   _wrgss_exec_bytecode(const uint8_t *buf,
 *                              size_t len,
 *                              const char *name);      // eval a RITE blob
 *   int   _wrgss_tick(void);                           // resume rgss_main
 *   void  _wrgss_shutdown(void);                       // free mrb state
 *
 * Plus diagnostic probes consumed by the JS runtime:
 *   int   _wrgss_debug_tick_probe(void);
 *   int   _wrgss_debug_game_running(void);
 *   int   _wrgss_debug_is_fiber(void);
 */

#include <mruby.h>
#include <mruby/array.h>
#include <mruby/compile.h>
#include <mruby/data.h>
#include <mruby/dump.h>
#include <mruby/error.h>
#include <mruby/hash.h>
#include <mruby/irep.h>
#include <mruby/proc.h>
#include <mruby/string.h>
#include <mruby/variable.h>

#include <emscripten.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "webrgss_imports.h"
#include "webrgss.h"

/* Bytecode of scripts/webrgss_prelude.rb (generated by mrbc -B). */
extern const uint8_t wrgss_prelude_irep[];

/* ---------------------------------------------------------------- globals */
static mrb_state *g_mrb           = NULL;
static int        g_tick_probe    = 0;   /* last tick state code (debug) */
static int        g_game_running  = 0;   /* 1 while main fiber alive */

/* ---------------------------------------------------------------- utils */

static void
wrgss_report_exception(mrb_state *mrb, const char *prefix)
{
  if (!mrb || !mrb->exc) return;

  char msg[4096];
  int off = 0;
  off += snprintf(msg + off, sizeof(msg) - off, "%s: ", prefix ? prefix : "error");

  /* Message */
  mrb_value exc = mrb_obj_value(mrb->exc);
  mrb_value msg_v = mrb_funcall(mrb, exc, "message", 0);
  if (mrb_string_p(msg_v)) {
    int n = snprintf(msg + off, sizeof(msg) - off, "%s", mrb_string_cstr(mrb, msg_v));
    if (n > 0) off += n;
  }

  /* Class */
  mrb_value klass_name = mrb_funcall(mrb, mrb_obj_value(mrb_obj_class(mrb, exc)), "to_s", 0);
  if (mrb_string_p(klass_name)) {
    int n = snprintf(msg + off, sizeof(msg) - off, " [%s]", mrb_string_cstr(mrb, klass_name));
    if (n > 0) off += n;
  }

  /* Backtrace (best effort, truncated) */
  mrb->exc = NULL;
  mrb_value bt = mrb_funcall(mrb, exc, "backtrace", 0);
  if (mrb_array_p(bt)) {
    off += snprintf(msg + off, sizeof(msg) - off, "\n\nTraceback:");
    mrb_int n = RARRAY_LEN(bt);
    for (mrb_int i = 0; i < n && off < (int)sizeof(msg) - 200; i++) {
      mrb_value line = mrb_ary_ref(mrb, bt, i);
      if (!mrb_string_p(line)) line = mrb_funcall(mrb, line, "to_s", 0);
      if (mrb_string_p(line)) {
        int w = snprintf(msg + off, sizeof(msg) - off, "\n  %s", mrb_string_cstr(mrb, line));
        if (w > 0) off += w;
      }
    }
  }
  /* Restore mrb->exc=NULL after reporting */
  mrb->exc = NULL;

  js_msgbox(msg);
}

/* ---------------------------------------------------------------- exports */

extern void wrgss_register_classes(mrb_state *mrb);

EMSCRIPTEN_KEEPALIVE
int
wrgss_init(void)
{
  if (g_mrb) return 0;

  mrb_state *mrb = mrb_open();
  if (!mrb) {
    js_msgbox("wrgss_init: mrb_open failed");
    return -1;
  }
  g_mrb = mrb;

  /* Register RGSS classes and modules (Color/Tone/Rect/Graphics/... etc.). */
  wrgss_register_classes(mrb);

  /* Load embedded prelude (webrgss_prelude.rb → RITE bytecode). */
  mrb_load_irep(mrb, wrgss_prelude_irep);
  if (mrb->exc) {
    wrgss_report_exception(mrb, "wrgss_init: prelude");
    return -2;
  }

  g_tick_probe   = 1;
  g_game_running = 0;
  return 0;
}

EMSCRIPTEN_KEEPALIVE
int
wrgss_exec_script(const char *src, const char *name)
{
  if (!g_mrb || !src) return -1;
  mrb_state *mrb = g_mrb;

  mrbc_context *cxt = mrbc_context_new(mrb);
  mrbc_filename(mrb, cxt, name ? name : "(script)");
  cxt->capture_errors = TRUE;

  int ai = mrb_gc_arena_save(mrb);
  mrb_load_string_cxt(mrb, src, cxt);
  int ret = 0;
  if (mrb->exc) {
    wrgss_report_exception(mrb, name ? name : "exec_script");
    ret = -1;
  }
  mrb_gc_arena_restore(mrb, ai);
  mrbc_context_free(mrb, cxt);
  return ret;
}

EMSCRIPTEN_KEEPALIVE
int
wrgss_exec_bytecode(const uint8_t *buf, size_t len, const char *name)
{
  if (!g_mrb || !buf || !len) return -1;
  mrb_state *mrb = g_mrb;
  (void)name; /* mruby irep loading doesn't keep source filename */

  int ai = mrb_gc_arena_save(mrb);
  mrb_load_irep(mrb, buf);
  int ret = 0;
  if (mrb->exc) {
    wrgss_report_exception(mrb, name ? name : "exec_bytecode");
    ret = -1;
  }
  mrb_gc_arena_restore(mrb, ai);
  return ret;
}

EMSCRIPTEN_KEEPALIVE
int
wrgss_tick(void)
{
  if (!g_mrb) { g_tick_probe = 10; return 0; }
  mrb_state *mrb = g_mrb;

  /* Call __wrgss_tick_internal defined in the prelude.
   * Returns 1 while the rgss_main fiber is alive, 0 otherwise. */
  int ai = mrb_gc_arena_save(mrb);
  mrb_value ret = mrb_funcall(mrb, mrb_top_self(mrb), "__wrgss_tick_internal", 0);
  if (mrb->exc) {
    wrgss_report_exception(mrb, "wrgss_tick");
    g_tick_probe = 21;
    g_game_running = 0;
    mrb_gc_arena_restore(mrb, ai);
    return 0;
  }
  mrb_gc_arena_restore(mrb, ai);

  int running = mrb_fixnum_p(ret) ? (int)mrb_fixnum(ret)
                : (mrb_bool(ret) ? 1 : 0);
  g_tick_probe   = running ? 20 : 21;
  g_game_running = running;
  return running;
}

EMSCRIPTEN_KEEPALIVE
void
wrgss_shutdown(void)
{
  if (!g_mrb) return;
  mrb_close(g_mrb);
  g_mrb = NULL;
  g_tick_probe = 99;
  g_game_running = 0;
}

/* ---------------------------------------------------------------- debug */

EMSCRIPTEN_KEEPALIVE int wrgss_debug_tick_probe(void)   { return g_tick_probe; }
EMSCRIPTEN_KEEPALIVE int wrgss_debug_game_running(void) { return g_game_running; }

EMSCRIPTEN_KEEPALIVE
int
wrgss_debug_is_fiber(void)
{
  if (!g_mrb) return 0;
  mrb_state *mrb = g_mrb;
  mrb_value main = mrb_gv_get(mrb, mrb_intern_lit(mrb, "$__wrgss_main_fiber"));
  return mrb_nil_p(main) ? 0 : 1;
}

/* ---------------------------------------------------------------- alloc */
EMSCRIPTEN_KEEPALIVE void *wrgss_alloc(size_t n) { return malloc(n); }
EMSCRIPTEN_KEEPALIVE void  wrgss_free(void *p)   { free(p); }

/* ---------------------------------------------------------------- global accessor */
mrb_state *wrgss_mrb(void) { return g_mrb; }
